### ISSUE TITLE
Refactoring: Change every print method with print_say method

### ISSUE THREAD

**Issue by StefanosChaliasos** [sukeesh/Jarvis#80] opened 2017-05-12 09:24 UTC
The print say method has three arguments: text, self and color. You can see the source code of the method [here](https://github.com/sukeesh/Jarvis/blob/master/Jarvis/utilities/GeneralUtilities.py)

**Comment by Josiah-DuBose** [comment] 2017-05-12 16:08
I can do this one as well...Do you mean every print method in every file?

**Comment by StefanosChaliasos** [comment] 2017-05-12 16:45
We want to use print_say method because it checks if the sound is enabled and then if the sound is enabled it use the voice method. You must give the self object as the second argument of the method every time you implement it. The first argument is the text to print and the third is the color (ex. Fore.BLUE, Fore.RED). We want to use the print_say method most of the times but not in very big message like the help_todo method (CmdInterpreter.py line 392). One example of what you have to do is in CmdInterpreter.py line 417: from `print(Fore.BLUE + '[!] Operating System Information' + Fore.RESET)` to `print_say('[!] Operating System Information', self, Fore.BLUE)`

**Comment by Josiah-DuBose** [comment] 2017-05-12 17:03
Okay. I'm having problems running Jarvis.py. When I run with python 2 I get "from colorama import Fore ImportError: No module named colorama" and when I run with python 3 I get "from engine import Engine ImportError: No module named 'engine'". I've tried installing requirements.txt in a virtual env and without one. Any thoughts about this? oh and I checked that colorama and Engine both exist and are up to date. Both of them are installed correctly as far as I can tell. Any thoughts?

**Comment by StefanosChaliasos** [comment] 2017-05-12 17:17
You can execute the command  `pip install -r requirements.txt` to be sure that all the package are installed. Have you checked if you can use colorama in an other simple python program. For example execute a foo.py with that code:
 `from colorama import Fore
  print(Fore.BLUE + "hello" + Fore.RESET)`. By the way we use python 2.

**Comment by Josiah-DuBose** [comment] 2017-05-12 18:42
yeah colorama works just fine in other files. Still won't work in Jarvis but I'll figure it out

**Comment by LuisFSilva** [comment] 2017-05-12 18:44
Are you on Windows? I had the same problem yesterday when I tried to get Jarvis running there

**Comment by Josiah-DuBose** [comment] 2017-05-12 18:45
No mac

**Comment by Josiah-DuBose** [comment] 2017-05-12 18:45
El captain

**Comment by Josiah-DuBose** [comment] 2017-05-12 19:08
new error, which means progress! ImportError: No module named gi

**Comment by Josiah-DuBose** [comment] 2017-05-12 19:18
Okay made it past the basic gi error but now the problem is this import line in Jarvis/Jarvis/packages/reminder.py
{code}
from gi import Notify
gi.require_version('Notify', '0.7')
{code}
this produces this error: "AttributeError: 'module' object has no attribute 'require_version'"
I've double and the syntax for using gi is correct.

**Comment by Josiah-DuBose** [comment] 2017-05-12 19:53
Any help or suggestions would be much appreciated.

**Comment by StefanosChaliasos** [comment] 2017-05-12 20:30
Unfortunately this is an unsolved bug #58 . Furthermore Jarvis doesn't have support for MacOSX #3 , there is an open PR about that issue #32 . A temporary solution is to install [virtual box](https://www.virtualbox.org/) and create an [ubuntu VM](https://www.youtube.com/watch?v=QkJmahizwO4) . It will be a major help if you could solve any of the issues #58 or #3

**Comment by Josiah-DuBose** [comment] 2017-05-12 20:33
Okay I'll take a look

**Comment by rarredon** [comment] 2017-05-28 00:20
Hi @Josiah-DuBose, are you still working on this issue? If not, I can take a stab at it. Let me know.

**Comment by Josiah-DuBose** [comment] 2017-05-28 00:50
I finished this awhile ago and was under the impression it had been merged. But now I see a commit that it needs to be rebased again. I'll take care of that so hopefully it will get merged this time and be closed.

**Comment by Josiah-DuBose** [comment] 2017-05-28 00:51
Disregard that last, different issue

**Comment by Josiah-DuBose** [comment] 2017-05-28 01:06
You can go for it, I've got a lot of work right now.

**Comment by rarredon** [comment] 2017-05-28 16:56
Two questions for clarification:

1) We would like to replace **ALL** print functions? For example, even those in help statements like the following?

```python
    def help_todo(self):
        """Print help about todo command."""
        print_say("Create your personal TODO list!", self)
        print("Supported Commands: todo <command>")
        print("\tadd [<index>] <todo - comment>, add comment <index> <comment>, add due <index> <time>")
        print("\tremove <index>")
        print("\tcomplete <index> [<completion>]")
        print("\tpriority <index> [<level>]")
        print("\tlist")
```

2) If a print function already had a Fore.COLOR passed, I went ahead and used that for the color argument in print_say. If a print function does not specify Fore.COLOR, should I omit the color argument?

**Comment by StefanosChaliasos** [comment] 2017-05-28 22:24
1. No we don't want it in help methods
2. A) Yes
2. B) No in that case don't give any argument

**Comment by rarredon** [comment] 2017-06-03 23:45
I'm having an issue replacing some of the `print()` calls with `print_say()`. It makes sense to use the keyword `self` in the definition of the Jarvis/CmdInterpreter class. However, outside of the class definitions, the `self` keyword does not make sense to use. I suppose I could create an instance of the Jarvis class every time I call `print_say` outside of the class defs, but that's probably not the best way to go about it. Do you have any ideas?

**Comment by StefanosChaliasos** [comment] 2017-06-04 16:50
Yes I agree with you. You could skip the print calls outside of the class Jarvis/CmdInterpreter. We could handle it in the future

**Closed** 2017-06-16 19:22 UTC
