### ISSUE TITLE
jarvis as a server

### ISSUE THREAD

**Issue by CiTRuS93** [sukeesh/Jarvis#709] opened 2020-06-14 13:18 UTC
add a new option to run jarvis as a server using Flask or Flask-rest so we can build personal web app.
for example:
add an option to run 
`Jarvis -server`
`* Running on http://127.0.0.1:5000/`

then we can use http get
`http://127.0.0.1:5000/api/v1/{user input string}`
or maybe socket will be a better solution for that.

**Comment by CiTRuS93** [comment] 2020-06-16 10:30
does like here mean "good idea" or "go do it"?

**Comment by pnhofmann** [comment] 2020-06-16 11:03
good idea ;). But could really have added a more meaningful text.

Is your issue related to #707? 

Anyway, I currently experimenting a bit restructuring Jarvis core. If I'm able to extract Jarvis Logic <-> Jarvis CLI output, yes, a flask-server should be possible without bigger issues, too.

**Comment by CiTRuS93** [comment] 2020-06-16 12:37
I don't think it's related to #707 , while #707 is about Jarvis logic, I'm talking about surrounding the Jarvis logic with server. basically adding a connection layer witch transfer Jarvis CLI throw web

**Comment by pnhofmann** [comment] 2020-06-25 10:18
Hi again!
Did push new branch introducing a new abstraction Jarvis logic <-> (multiple) front-ends
https://github.com/sukeesh/Jarvis/tree/restructure/jarviscli/ui

I am confident Jarvis web server can be implemented with just a view lines of code; will take a closer look soon.

**Comment by evamy** [comment] 2020-07-15 15:06
I was trying to add a home server of sorts in Jarvis, but for that I require the super/parent class as BaseHttpRequestHandler for the HomeServer class, something like this:

```
from http.server import BaseHTTPRequestHandler

@require(network=True)
@plugin("home server")
class HomeServer(BaseHTTPRequestHandler):

    def __init__(self, request, client_address, server):
        self.request_handler = BaseHTTPRequestHandler(request, client_address, server)
        self.devices = dict()
        self.app_logins = dict()

```

The problem is, its `__init__` requires 3 parameters. Can you suggest a way for it ? I tried to look into other plugins but did not find something similar done anywhere else....

Thanks!

**Comment by pnhofmann** [comment] 2020-07-15 19:59
Hi!
plugins do not support any ``__init__`` - parameters. But don't think, ``home server`` should be a plugin. Should be implemented as an alternative way to run Jarvis. Similar to https://github.com/sukeesh/Jarvis/blob/restructure/jarviscli/ui/cmd_interpreter.py

The relevant code would be something like:
```
from main import build_plugin_manager

class CmdInterpreterJarvisAPI():
    def __init__(self, cmd_interpreter):
        super().__init__()
        self.cmd_interpreter = cmd_interpreter

    def say(self, text, color=''):
        # TO IMPLEMENT

    def input(self, prompt="", color=""):
        # TO IMPLEMENT

    def exit(self):
        # TO IMPLEMENT

class HomeServer(BaseHTTPRequestHandler):

    def __init__(self, request, client_address, server):
        super().__init__(request, client_address, server)
        self.devices = dict()
        self.app_logins = dict()

        language_parser = snips.LanguageParser()
        plugin_manager = build_plugin_manager()
        self._jarvis = Jarvis(langugage_parser, plugin_manager)

        _api_io = HomeServerJarvisAPI(self)
        self._api = self._jarvis.register_io(_api_io)

        # now we can execute commands using
        self._jarvis.execute_once(user_typed_command)
```

Plus a new script ``run_server.py`` That somehow calls something similar to : https://github.com/sukeesh/Jarvis/blob/restructure/jarviscli/main.py#L15
But with HomeServer instead CmdInterpreter.

**Comment by evamy** [comment] 2020-07-16 13:45
@pnhofmann 
I think even if we are using jarvis with the command line interface, we should be able to start and stop the home server.

So, I think currently there are 2 possibilities for us:

1. We consider it as a ui:
1.1 We will be able to separately start a home server and send command line instructions to it to which it can respond. or,
1.2 We can consider starting the home server capability coupled with the command line, but I think we may lose the ability to start or stop or restart the server at will.

2. We consider it as a plugin:
2.1 We gain the ability to start or stop or restart the server at will, within any other ui. and
2.2 We will be able to send command line instructions to it to which it can respond to --> but this may require extra code for it.

Both of those possibilities do not cover all the scenarios. UI, though does cover most of the scenarios, will not be able to cover all of those. 
Might I suggest a third possibility that we attempt to implement which may cover all scenarios:

We consider it a UI Service, instead of UI.
- Gives us ability to start/stop/restart server at will, using any interface
- Will still take cmd instructions/(or whatever interface we started it with) and serve client requests as well (server threads!).
- And we can always set a cmd line parameter to start whatever interface with the server itself.

Please let me know what you think.

**Comment by pnhofmann** [comment] 2020-07-17 20:44
> I think even if we are using jarvis with the command line interface, we should be able to start and stop the home server.

That definitely explains your 'as a plugin'-thought.


> We consider it a UI Service, instead of UI.

Yes, possible.

If I understand you correctly, cmd interface and server interface should work 100% independent. Like: While Server is running a task (and maybe even asking for user input?), the cmd interface can run a completely different task, that is not affected from server task in any way.

And we are probably not talking about one Thread / UI Service. Imagine, 3 Clients A, B and C connect. Jarvis will most likely need 3 Thread with 3 independent Server UI-Services to handle all 3 clients simultaneous. So sure! I see no issue, having 4th UI (like CmdInterpreter).
But would implement the plugins to start / stop / restart  Server Service(s) last. First we need the Server UI Service - which basically would be a UI (but running in a thread).

**Comment by CiTRuS93** [comment] 2020-07-19 13:36
hey there!
I really forgot about this issue.

instead of using BaseHTTPRequestHandler, why won't we use flask?
something like this:

`@app.route('/command')
def command():
    message = request.get_json()
    cmd_interpreter = jarvis_dict[message['id']]
    command = " ".join(message['command']).strip()
    cmd_interpreter.executor(command)

@app.route('/connect')
def connect():
    
    global_users_id +=1
    #language_parser = default.DefaultLanguageParser()
    language_parser = snips.LanguageParser()
    plugin_manager = build_plugin_manager()
    jarvis = Jarvis(language_parser, plugin_manager)
    cmd_interpreter = CmdInterpreter(jarvis)
    
    jarvis_dict[global_users_id]=cmd_interpreter
    return jsonify({'user_id':global_users_id})

if __name__ == '__main__':
    app.run(threaded=True)`

one problem that I can think of is that we need to override Jarvis.say() to send response to the client instead of printing.
maybe use sockets along http requests.

**Comment by evamy** [comment] 2020-07-19 20:05
@pnhofmann 
I gave this more thought, shouldn't all the UI be 100% independent of each other ?
Shouldn't we be able to enable chat/voice/cmd line interface all independently of themselves ?
And while being on the cmd line, I should be able to invoke the same command that I should be able to either on chat or via server, or via voice.

So, we can actually make cmd line the base (or make it the base when you are on the laptop, and make chat the base when you are on the phone/iphone, and or if in future deployed to a device make voice the base -- or just give the ability to select application base during start), and provide enable/disable options for the other types of interfaces.

**Comment by pnhofmann** [comment] 2020-07-19 20:51
@evamy 

>  I gave this more thought, shouldn't all the UI be 100% independent of each other ?

Yep

> So, we can actually make cmd line the base 

No problem with that.

@CiTRuS93 

> instead of using BaseHTTPRequestHandler, why won't we use flask?

+1

**Comment by CiTRuS93** [comment] 2020-07-22 08:41
hey again,
I've build some simple Flask server but for some reason I can't run it with Jarvis,
some virtual environment problem that I can't figure out.
 I did test it with some Cmd Interpreter stub successfully.

@pnhofmann 
should I push it?

**Comment by evamy** [comment] 2020-07-22 15:30
@CiTRuS93 
I can try taking a look at it if you'd like ?

**Comment by CiTRuS93** [comment] 2020-07-22 16:05
@evamy 
that will be awesome

**Comment by evamy** [comment] 2020-07-22 17:46
So, I got the home server running with Jarvis:
<img width="854" alt="Screen Shot 2020-07-22 at 12 44 47" src="https://user-images.githubusercontent.com/5526025/88210044-30036900-cc19-11ea-9b6c-d2ced884c7e2.png">

@pnhofmann 
Suggestion needed: Home server application is in the UI, will serve as the UI, but to start it would be a plugin, right ?
I'm not able to think another way to do it. Please suggest something if you have in mind.

**Comment by CiTRuS93** [comment] 2020-07-22 18:08
I don't think we should run the server as plug in, instead we should run the server if we're getting server flag:
`>>Jarvis -server     #will run jarvis as server`
`>>Jarvis     #will run jarvis as usual`

**Comment by evamy** [comment] 2020-07-22 18:59
@CiTRuS93 
I think we should be able to start, stop, restart the server while jarvis is already running. Which is what brings me to server start as a plugin, instead of directly.

**Comment by CiTRuS93** [comment] 2020-07-22 20:03
So we'll be managing several Jarvis instances inside Jarvis?

**Comment by evamy** [comment] 2020-07-22 20:52
@CiTRuS93 
So, think of it in terms of a microservice all reporting to the same base service.
There is just one instance running, which can spawn threads, those threads can either provide services/ui, or just do some task and finish per the task end.

**Comment by evamy** [comment] 2020-07-23 16:06
@pnhofmann 
Let me know what you think on how you would send a request to start/stop/restart the server.

**Comment by pnhofmann** [comment] 2020-07-23 17:40
> I think we should be able to start, stop, restart the server while jarvis is already running. 

Yes, but it would be possible to create a plugin something like that:

```
@plugin('start server')
def start_server(jarvis, s):
    os.system('./jarvis -server)
```

or

```
from jarviscli import main
@plugin('start server')
def start_server(jarvis, s):
    threading.Thread(run=main, run_as_server=True)
```

Plus equivalent for stop / restart and some simple logic to check if server is already running.

But in general, would say the server is Jarvis core functionality rather than a plugin. But like shown above, this does not contradict the idea of being able to start / stop / restart Jarvis server while Jarvis is already running!

**Comment by evamy** [comment] 2020-07-24 13:00
I was going for the second type! Cool, thanks! Now I can build on it!

**Comment by evamy** [comment] 2020-07-25 13:13
So, for the app route directive, I was thinking of something like this:

```
@server_app.route('/plugin/start')
def command():
    uid = int(request.args.get('id'))
    command = request.args.get('command')

    cmd_interpreter = jarvis_dict[uid]
    command = " ".join(command).strip()

    # override the stdout so every print will be sent to the client
    with io.StringIO() as buf, redirect_stdout(buf):
        cmd_interpreter.executor(command)
        output = buf.getvalue()
    return jsonify({'response': output})
```

where the end points are all made of plugin names, and calling them just calls the plugin.
There can be an extra request parameter which includes extra parameters required.

Thoughts on this @pnhofmann or @CiTRuS93.
Sure we could also just take a string command as well.

**Comment by pnhofmann** [comment] 2020-07-25 15:32
> where the end points are all made of plugin names, and calling them just calls the plugin.

Hmm, like this idea. This provides a much cleaner api than parsing text like ``jarvis, please call start``. With ``curl http://server/plugin/start?param=x`` it is clear, what the server does.

One final hint, because I say your edit: There is jarvis.register_io(). Use like this:

```
ServerIO:
    def say(self, text, color=''):
        # TO IMPLEMENT FIRST
        pass
 
    def input(self, prompt="", color=""):
        # TO IMPLEMENT PROBABLY LATER
        # because 'input' might be tricky to implement
         pass

    def exit(self):
        # STOP SERVER
        pass

jarvis = Jarvis(language_parser, plugin_manager)
jarvis.register_io(ServerIO())
```

=> You don't need to overwrite stdout. With register_io you can archive, that this method ``say`` is directly called.

**Comment by evamy** [comment] 2020-07-25 18:18
@pnhofmann 

New [branch](https://github.com/MLDaily/Jarvis/tree/restructure) edits on my end.
^ this is what I currently have
Not yet been able to make everything an endpoint (working on it).

> > where the end points are all made of plugin names, and calling them just calls the plugin.

> Hmm, like this idea. This provides a much cleaner api than parsing text like jarvis, please call start. With a request curl http://server/plugin/start?param=x it is crystal clear, what the server should do.

The only drawback of this idea is that the client will need to already have parsed the action into the calling url.

```
http://server:port/movie/year?s=random
```
Will have to be derived at the client, instead of the server.
If the client is not able to make a deduction, we can have the server take a look at it in another endpoint.

I have also added a health endpoint, in case we may need to check if the server is up and running or not from a different device.

I did not understand your point on the register_io. Are we trying to make a jarvis response function/class which can work across UIs ?

Context on why I'm working on this:
I have a home server that runs all my wifi modules (home automation stuff, arduino etc.)
This can be a replacement for that, and I can make the server do much more now, and at the same time, add many more types of clients (temp sensors, time displays etc.)

But even if I did not have that in place, jarvis is one thing I would always love to work on! There are so many features that I have already started working on since I found this library. One of them being a password changer/unlock laptop using phone/trigger password change of one device from another, which may also require multiple devices (including android and iphone set up with this). 

All in all, I'm glad someone gave me a base with this Jarvis!

**Comment by CiTRuS93** [comment] 2020-07-26 09:28
@evamy 

I've noticed before your edit that u want to use the server as a home server home automation. I don't think that http server will give u all the functionality that u want, maybe we need to add some socket based chat room (like AWS pubsub for example)?

**Comment by pnhofmann** [comment] 2020-07-26 10:35
> The only drawback of this idea is that the client will need to already have parsed the action into the calling url.

This is a solvable issue.

```
@plugin('talk')
def talk(jarvis, s):
    jarvis.eval(s)
```

And you can ask stuff like: ``http://server:port/talk?s=Jarvis what year did the movie inception release``

(Note: ``jarvis.eval(s)`` is currently broken on restructure branch. Will take a look later)

 > I did not understand your point on the register_io. Are we trying to make a jarvis response function/class which can work across UIs ?

Yep, a standardized interface since differed UIs need different ways to ``say`` and ``input``. With register_io Uis may ``patch`` in their implementation of these methods.

> New branch edits on my end.

Nice!

Strange I can't send PR against this branch (``MLDaily`` just does not show up for base repository).

So, this is the funny line:
https://github.com/MLDaily/Jarvis/blob/restructure/jarviscli/ui/server/server.py#L44

The plugin-function needs to be 'wrapped' a bit, that it's called correctly. Note that for calling plugins, ``server`` also needs it's own instance of ``jarvis``.

Did some quick coding:

https://github.com/pnhofmann/Jarvis/commit/8e426611ce759bb97783c3ed4743a17bd065b699 

Obviously every plugin that calls ``input`` does not work. But I could already archive: 

```
> curl localhost:8008/roll
---
|1|
---
```

**Comment by evamy** [comment] 2020-07-26 16:36
@CiTRuS93 
> I don't think that http server will give u all the functionality that u want, maybe we need to add some socket based chat room (like AWS pubsub for example) that can function as a Iot server?

I think that problem can be solved using plugins. 
I'll just have to add a proper plugin for the devices that I use(d).

Example, I can add a plugin like:
`wifimodule introduce` with `@require(server=True)`
and then from the `wifimodule` client, I can send a POST request for introducing the device onto the server and then the server can store information in its memory of the devices that introduced themselves.

> Strange I can't send PR against this branch (MLDaily just does not show up for base repository).

That may be because of org access issues.

> Did some quick coding:
> pnhofmann@8e42661

I have more edits on my end, will merge these. Over the top these look super good.
I was also trying to avoid doing a wrap function and find a way around it. May need to sync back on that part!

Another question actually:

I was trying to add rules as:

```
/movie/year
/movie/director
/movie/<something>

or 

/update/some_random_update_feature

etc.
```
the recursive code that I have, adds as:

```
/movie_year
/movie_director
/movie_<something>

or 

/update_some_random_update_feature
etc.
```

Could you suggest changes ? (or look into that ?)

**Comment by evamy** [comment] 2020-07-27 21:16
@pnhofmann 
I looked at the code in your commit.

If we change the jarvis main process to the server process, what happens to the base process (cmd line process), shouldn't we be able to keep that running ?

**Comment by evamy** [comment] 2020-07-29 14:31
@pnhofmann 
Question: will voice also get moved to the ui package ? (it is in fact a UI...)
Can we treat the server similar to voice ??

**Comment by pnhofmann** [comment] 2020-07-29 15:12
> what happens to the base process (cmd line process), shouldn't we be able to keep that running ?

Is still running (try typing stuff, Jarvis will answer!). It is just a bit confusing, because server info is printed to stdout. Which is fine for debugging, but ultimately we'll need to redirect everything form server to a log file.

> Could you suggest changes ? (or look into that ?)

Probably too trivial ;).

``endpoint_string = "/" + '_'.join(re.findall(r"[\w']+", plugin.get_name()))``
->
``endpoint_string = "/" + '/'.join(re.findall(r"[\w']+", plugin.get_name()))``

> Question: will voice also get moved to the ui package ? (it is in fact a UI...)

Interesting question. Would make sense. It's actually 1/2 a ui, because it's only text to speech. But with voice recognition (work in progress...) it is. But then our assumption "One Jarvis instance = One UI" would no longer hold. Like: User is using both CmdInterpreter and Voice. Expected behavior: User both reads and hears Jarvis output.

Have to think about; maybe it would actually be best to allow multiple ui on one Jarvis instance.

**Comment by evamy** [comment] 2020-07-29 15:41
@pnhofmann 
So, here's what I have on my mind (and it's kind of cluttered, so maybe writing it down and discussing here will help me too):

- The way we have the current voice settings, is how it would be best to keep it. `voice` package will move to `ui` but enable and disable voice should be available just the way it is currently, and we can spawn a thread/process for the UI.
- So, like `jarvis.speech` accesses `voice`, the same way we access `server` package using `jarvis.server`, spawn/respawn a thread/process when needed/enabled/started/restarted.
- Once we have that in place, we can add platforms `[SERVER, VOICE]`.
- Whenever `jarvis.server` is enabled/started, we enable all the plugins that can only be served on a server. (like connecting a client device with request body or something)
- Whenever `jarvis.speech` is enabled/started, we enable all the plugins which would otherwise be useless on the command line (plugins like: `play a lullaby` will now be more useful, if and when they are added).

What do you think about this ? It's not complete yet, but I'm still in the process of discovering more as I keep coding. Currently jarvis and jarvisApi difference are kind of confusing me.

**Comment by evamy** [comment] 2020-07-29 16:53
> Probably too trivial ;).
> 
> `endpoint_string = "/" + '_'.join(re.findall(r"[\w']+", plugin.get_name()))`
> ->
> `endpoint_string = "/" + '/'.join(re.findall(r"[\w']+", plugin.get_name()))`

That changes this:
`/update_some_random_update_feature`
to
`/update/some/random/update/feature`
where we would prefer
`/update/some_random_update_feature`

**Comment by pnhofmann** [comment] 2020-07-29 18:16
Does not, original plugin name would be: ``update some_random_update_feature``. The re.findall() returns - ``['update', 'some_random_update_feature']`` - since '_' is in '\w'. And the join returns: ``update/some_random_update_feature``

> Once we have that in place, we can add platforms [SERVER, VOICE]

More a ``require()`` tag, but yes! Also agree with rest of your comment.

> Currently jarvis and jarvisApi difference are kind of confusing me.

I don't even know if this was a clever decision.

Jarvis_api is what is passed when plugins are called. To provide some functionality like ``say``, ``input``, ``notification``, ... plugins need. These functions in jarvis_api are called within plugins and from nowhere else Probably disadvantageous naming, because the jarvis_api object inside a plugin is usually named just ``jarvis``.

Maybe to illustrate, this is sort of a cycle:

```
* UI (owns jarvis_io) calls jarvis.execute_once()
* Jarvis (owns jarvis_api) calls plugin run method with jarvis_api as parameter
* plugin calls jarvis_api say / input-method
* jarvis_api calls jarvis_io (previously set with jarvis.register_io) method
* jarvis_io reports back to UI
```

Hey, but this is just some things I came up with - so no claim this solution is in any way 'good' ;).

**Comment by evamy** [comment] 2020-07-29 18:36
> Does not, original plugin name would be: `update some_random_update_feature`. The re.findall() returns - `['update', 'some_random_update_feature']` - since '_' is in '\w'. And the join returns: `update/some_random_update_feature`

Umm, maybe I did not explain this properly.

the original plugin name is `update some random update feature`

**Comment by pnhofmann** [comment] 2020-07-29 20:18
> the original plugin name is update some random update feature

Ok, in this case ``/update/some/random/update/feature`` is actually what I'd expect. My current design does not implement spaces inside plugin-names.
Call a plugin ``update some random update feature`` and you actually create a plugin ``update`` with sub-command ``some`` with sub-command ``random`` with sub-command ``update`` with sub-command ``feature``.

**Comment by evamy** [comment] 2020-08-05 13:35
Okay, that might be the reason why I get four of these:
```
{'route': '/country_with_dial_code', 'endpoint': '/country_with_dial_code', 'func': <function JarvisServer._wrap_plugin.<locals>._run at 0x11fac9dd0>}, 
{'route': '/country_with_dial_code', 'endpoint': '/country_with_dial_code', 'func': <function JarvisServer._wrap_plugin.<locals>._run at 0x11fac9e60>}, 
{'route': '/country_with_dial_code', 'endpoint': '/country_with_dial_code', 'func': <function JarvisServer._wrap_plugin.<locals>._run at 0x11fac9ef0>}, 
{'route': '/country_with_dial_code', 'endpoint': '/country_with_dial_code', 'func': <function JarvisServer._wrap_plugin.<locals>._run at 0x11fac9f80>}, 
{'route': '/country_with_dial_code', 'endpoint': '/country_with_dial_code', 'func': <function JarvisServer._wrap_plugin.<locals>._run at 0x11fac7050>}, 
{'route': '/country_with_dial_code', 'endpoint': '/country_with_dial_code', 'func': <function JarvisServer._wrap_plugin.<locals>._run at 0x11fac70e0>}, 
```

notice that all are different plugins (by their hash codes)

**Comment by Curiouspaul1** [comment] 2020-10-01 19:42
Is someone working on this already?

**Comment by evamy** [comment] 2020-10-01 19:48
@Curiouspaul1 I kinda am. I'm hoping to get this sorted out by the end of this month, if possible

**Comment by pnhofmann** [comment] 2022-12-26 20:59
Closing since this is merged in dev branch

**Closed by pnhofmann** 2022-12-26 20:59 UTC
