### ISSUE TITLE
Missing two packages (PyPDF2 and fasttext) upon a clean installation

### ISSUE THREAD

**Issue by saleguas** [sukeesh/Jarvis#922] opened 2022-01-28 01:47 UTC
After doing a fresh install of Jarvis  on my Windows 10 computer, I noticed that the default project expects PyPDF2 and fasttext otherwise It'll throw an ugly error message. 

![image](https://user-images.githubusercontent.com/42396136/151472586-84d1fecc-2a31-450e-958d-e3a4ab12087d.png)

I don't think this should be intended behavior, as the solution seems to be quite trivial.

**Comment by saleguas** [comment] 2022-01-28 01:50
I created a pull request #923 to fix this issue

**Comment by pnhofmann** [comment] 2022-01-28 21:04
Hi, thanks for reporting this issue!

> as the solution seems to be quite trivial.

Yeah, not hard - but not quite that trivial. The issue is, PyPDF2 and fasttext aren't pure python, but require native software.

We think Jarvis should run with pure-python with no platform-specific dependencies - so running Jarvis this way is indeed intended.

But I agree: The output is ugly.

The expected behaviour would be, that the depended plugins are listed as disabled plugins (the part "26 plugins disabled. More information: status")

What we have to think of: We cannot write our file like this:

```
import fasttext

@plugin('foo'):
def x(jarvis, s):
    # (...)
```

since the failed import won't let us execute anything below this line.

Probably just add a try-except around the fasttext and use the @require tag to disable plugin if fasttext import failed...

**Comment by pnhofmann** [comment] 2022-12-22 18:54
Fixed on master

**Closed by pnhofmann** 2022-12-22 18:54 UTC
